[project]
name = "pixi-lock-reproducible"
version = "0.1.0"
description = "Add a short description here"
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.12.4,<3.13"

[pypi-dependencies]
contourpy = "*"
